MCU = RP2040
BOOTLOADER = rp2040

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no

ENCODER_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes